//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JG_2017.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JG_2017.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a About Me.
        /// </summary>
        public static string About_me {
            get {
                return ResourceManager.GetString("About_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Get to know me more.
        /// </summary>
        public static string BtAboutMe_Home {
            get {
                return ResourceManager.GetString("BtAboutMe_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a en.
        /// </summary>
        public static string ConfigLang {
            get {
                return ResourceManager.GetString("ConfigLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Copyright © 2017 - All rights reserved..
        /// </summary>
        public static string Copyright_Footer {
            get {
                return ResourceManager.GetString("Copyright_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &quot;The man who cannot believe in himself cannot believe in anything else.” Roy L. Smith.
        /// </summary>
        public static string MessageTextHeader {
            get {
                return ResourceManager.GetString("MessageTextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Online Portfolio Jones Guidini - (Web Developer &amp; .NET Developer ).
        /// </summary>
        public static string MetaTagsDescription {
            get {
                return ResourceManager.GetString("MetaTagsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a websites, web, development, programmer, web developer, system analyst, software analyst, dot net developer, .net developer, Brasilia, df, your site, product, designer, design, C#,.NET, asp, mvc, php, ingles, magento, html, css, xml, javascript, angularjs, .net core.
        /// </summary>
        public static string MetaTagsKeywords {
            get {
                return ResourceManager.GetString("MetaTagsKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a JONES GUIDINI - WEBDEVELOPER&amp; .NET DEVELOPER.
        /// </summary>
        public static string MetaTagsSiteName {
            get {
                return ResourceManager.GetString("MetaTagsSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a JONES GUIDINI - WEBDEVELOPER&amp; .NET DEVELOPER.
        /// </summary>
        public static string MetaTagsTitle {
            get {
                return ResourceManager.GetString("MetaTagsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Portfolio.
        /// </summary>
        public static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Skills.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;p&gt;Hi my name is Jones Guidini. I&apos;ve been a technology enthusiast since I was a kid. I was that kind of boy who usually opened the toys to see how they worked from the inside. Time passes but the passion for technology only increases. What always keeps me willing to learn more and more is the curiosity. Due to it, I could meet the amazing web developing world. When I first started reading my first HTML book I even didn&apos;t have a computer. &lt;/p&gt;
        ///
        ///&lt;p&gt;I have a Bachelor&apos;s degree in Analysis Systems, an MBA in S [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string SubInfoPage_AboutMe {
            get {
                return ResourceManager.GetString("SubInfoPage_AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;p&gt;If you want to talk to me you can use any of these alternatives below. Please, choose the most convenient for you. I look forward to receiving your message and I promise I&apos;ll answer it as fast as possible. &lt;/p&gt;.
        /// </summary>
        public static string SubInfoPage_Contact {
            get {
                return ResourceManager.GetString("SubInfoPage_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;p&gt;As a web developer with over 12 years of valuable experience, I’ve been working hard to improve my knowledge and skills in order to offer the best I can. Over the years, I’ve gained a lot of experience working with different approaches related to web development. I started as a web designer using front-end technologies such as HTML, CSS, JavaScript, Photoshop, Illustrator and others. Some years later, I began to explore back-end technologies such as PHP, MySQL and others. Finally, I met the giant .NET wo [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string SubInfoPage_Home {
            get {
                return ResourceManager.GetString("SubInfoPage_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;p&gt;If you are curious about what I’ve done as web developer, you’re in the right place. Here you can check some of my work. You can see that it is organized into categories. Therefore, if you are interested in seeing a specific one, click on the name of the category and it will open a list of work. &lt;/p&gt;.
        /// </summary>
        public static string SubInfoPage_Portfolio {
            get {
                return ResourceManager.GetString("SubInfoPage_Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;p&gt;Throughout these twelve years, I have been learning about technologies largely used in web development. As a Front and Back End developer, I have gathered knowledge in many different technologies. Some of them were discontinued and new ones were added. In order to make it easy to measure my knowledge, I listed some of these technologies below, you can see them by category. Enjoy yourself!&lt;/p&gt;.
        /// </summary>
        public static string SubInfoPage_Skills {
            get {
                return ResourceManager.GetString("SubInfoPage_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GRAPHIC ARTS - ENVELOPES.
        /// </summary>
        public static string SubLink_envelopes_Portfolio {
            get {
                return ResourceManager.GetString("SubLink_envelopes_Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GRAPHIC ARTS - LOGOS.
        /// </summary>
        public static string SubLink_logos_Portfolio {
            get {
                return ResourceManager.GetString("SubLink_logos_Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GRAPHIC ARTS - OTHERS.
        /// </summary>
        public static string SubLink_others_Portfolio {
            get {
                return ResourceManager.GetString("SubLink_others_Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WEBSITES / SYSTEMS.
        /// </summary>
        public static string SubLink_websites_Portfolio {
            get {
                return ResourceManager.GetString("SubLink_websites_Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a BACKEND TECHNOLOGIES.
        /// </summary>
        public static string Subtitle_backend_Skill {
            get {
                return ResourceManager.GetString("Subtitle_backend_Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DESIGN TOOLS.
        /// </summary>
        public static string Subtitle_designtools_Skills {
            get {
                return ResourceManager.GetString("Subtitle_designtools_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FRONTEND TECHNOLOGIES.
        /// </summary>
        public static string Subtitle_frontend_Skills {
            get {
                return ResourceManager.GetString("Subtitle_frontend_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HOW CAN YOU TALK TO ME?.
        /// </summary>
        public static string Subtitle_howto_Contact {
            get {
                return ResourceManager.GetString("Subtitle_howto_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IDE&apos;S AND CODE EDITORS.
        /// </summary>
        public static string Subtitle_ides_Skills {
            get {
                return ResourceManager.GetString("Subtitle_ides_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ENGLISH.
        /// </summary>
        public static string Subtitle_language_eng_Skills {
            get {
                return ResourceManager.GetString("Subtitle_language_eng_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PORTUGUESE.
        /// </summary>
        public static string Subtitle_language_pt_Skills {
            get {
                return ResourceManager.GetString("Subtitle_language_pt_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LANGUAGE SKILLS.
        /// </summary>
        public static string Subtitle_language_Skills {
            get {
                return ResourceManager.GetString("Subtitle_language_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VERSIONING TOOLS.
        /// </summary>
        public static string Subtitle_versioningtools_Skills {
            get {
                return ResourceManager.GetString("Subtitle_versioningtools_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Open envelope.
        /// </summary>
        public static string SubtitleLink_envelope_Portfolio {
            get {
                return ResourceManager.GetString("SubtitleLink_envelope_Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Open logo.
        /// </summary>
        public static string SubtitleLink_logo_Portfolio {
            get {
                return ResourceManager.GetString("SubtitleLink_logo_Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Open graphic art.
        /// </summary>
        public static string SubtitleLink_others_Portfolio {
            get {
                return ResourceManager.GetString("SubtitleLink_others_Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Visit website.
        /// </summary>
        public static string SubtitleLink_website_Portfolio {
            get {
                return ResourceManager.GetString("SubtitleLink_website_Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PHONE.
        /// </summary>
        public static string Tag_phone_Contact {
            get {
                return ResourceManager.GetString("Tag_phone_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Who am I?.
        /// </summary>
        public static string TitlePage_AboutMe {
            get {
                return ResourceManager.GetString("TitlePage_AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Do you want to talk to me?.
        /// </summary>
        public static string TitlePage_Contact {
            get {
                return ResourceManager.GetString("TitlePage_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Who am I?.
        /// </summary>
        public static string TitlePage_Home {
            get {
                return ResourceManager.GetString("TitlePage_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a What Have I done?.
        /// </summary>
        public static string TitlePage_Portfolio {
            get {
                return ResourceManager.GetString("TitlePage_Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a What do I know?.
        /// </summary>
        public static string TitlePage_Skills {
            get {
                return ResourceManager.GetString("TitlePage_Skills", resourceCulture);
            }
        }
    }
}
